apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-default-volume
  annotations:
    pv.beta.kubernetes.io/gid: "592"
spec:
  storageClassName: ""
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
