apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-default-volume
spec:
  storageClassName: ""
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.40.101
    iqn: iqn.2000-01.com.synology:kubeSAN.Target-1.5a052aef9b
    lun: 1
    fsType: 'ext4'
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
