apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-nfs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-nfs
    spec:
      containers:
        - name: postgres
          image: postgres:10.9
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
              subPath: postgres
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-nfs-claim
