- name: initialize the cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /root/cluster_initialized.txt
  register: kubeadm_init_raw

- name: save kubeadm init output to a file
  copy:
    content: "stdout:\n{{ kubeadm_init_raw.stdout }}\n\nstderr:\n{{ kubeadm_init_raw.stderr }}"
    dest: /root/cluster_initialized.txt

- name: create .kube directory
  become: yes
  become_user: eduard
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/eduard/.kube/config
